// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqTO6Z01b88YM36w1qpns8pnkJ7xhQxBQ',
    appId: '1:1078998892043:android:7caf1c076b4d7d9225d10e',
    messagingSenderId: '1078998892043',
    projectId: 'sos-ffc0c',
    storageBucket: 'sos-ffc0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR7IfqndJnE1cGi5BJCVkU4_Ks2PXGsu8',
    appId: '1:1078998892043:ios:f137bbd6e3a8aea225d10e',
    messagingSenderId: '1078998892043',
    projectId: 'sos-ffc0c',
    storageBucket: 'sos-ffc0c.firebasestorage.app',
    iosBundleId: 'com.example.sosBebeProfilBebeDoctor',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFRlUqoTfG9e0-oqHgPfJKPldB1ukaMc',
    appId: '1:1078998892043:web:f43075107d51198c25d10e',
    messagingSenderId: '1078998892043',
    projectId: 'sos-ffc0c',
    authDomain: 'sos-ffc0c.firebaseapp.com',
    storageBucket: 'sos-ffc0c.firebasestorage.app',
    measurementId: 'G-51J2QC08DZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR7IfqndJnE1cGi5BJCVkU4_Ks2PXGsu8',
    appId: '1:1078998892043:ios:f137bbd6e3a8aea225d10e',
    messagingSenderId: '1078998892043',
    projectId: 'sos-ffc0c',
    storageBucket: 'sos-ffc0c.firebasestorage.app',
    iosBundleId: 'com.example.sosBebeProfilBebeDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvFRlUqoTfG9e0-oqHgPfJKPldB1ukaMc',
    appId: '1:1078998892043:web:ed753ce298cd87b225d10e',
    messagingSenderId: '1078998892043',
    projectId: 'sos-ffc0c',
    authDomain: 'sos-ffc0c.firebaseapp.com',
    storageBucket: 'sos-ffc0c.firebasestorage.app',
    measurementId: 'G-BHYFMTHZ3J',
  );

}