// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMO_7L9bjkMZP7kEyqyOgEHH7PkKgG0s0',
    appId: '1:629418451122:android:ab37d0ca5c735f81caa9ab',
    messagingSenderId: '629418451122',
    projectId: 'sos-bebe-pacient',
    storageBucket: 'sos-bebe-pacient.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ1T4V6i3QzXQYePAQDkL5SzwDqxovNaA',
    appId: '1:629418451122:ios:1a405639a0a9012dcaa9ab',
    messagingSenderId: '629418451122',
    projectId: 'sos-bebe-pacient',
    storageBucket: 'sos-bebe-pacient.appspot.com',
    androidClientId: '629418451122-0a0mttatvosruoc955ro87ajeal5r8oq.apps.googleusercontent.com',
    iosClientId: '629418451122-n2ivor36630aorsmdab8hcpnibo3sbds.apps.googleusercontent.com',
    iosBundleId: 'com.example.sosBebeProfilBebeDoctor',
  );

}